sudo: false
language: node_js
addons:
  chrome: stable
os:
  - linux
  - osx
node_js:
  - '6'
  - '7'
  - 'node'
script:
  - npm test
  - npm run-script test2

#cache:
#  directories:
#    - node_modules
